// Mocks generated by Mockito 5.4.6 from annotations
// in app_froid/test/features/lfl_volume/domain/usecases/calculate_lfl_volume_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_froid/core/error/failures.dart' as _i5;
import 'package:app_froid/features/lfl_volume/domain/entities/flammable_fluid.dart'
    as _i8;
import 'package:app_froid/features/lfl_volume/domain/entities/lfl_parameters.dart'
    as _i7;
import 'package:app_froid/features/lfl_volume/domain/entities/lfl_result.dart'
    as _i6;
import 'package:app_froid/features/lfl_volume/domain/repositories/lfl_volume_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LflVolumeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLflVolumeRepository extends _i1.Mock
    implements _i3.LflVolumeRepository {
  MockLflVolumeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LflResult>> calculateLflVolume(
    _i7.LflParameters? parameters,
    double? safetyFactor,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateLflVolume, [parameters, safetyFactor]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.LflResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.LflResult>(
                    this,
                    Invocation.method(#calculateLflVolume, [
                      parameters,
                      safetyFactor,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.LflResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.FlammableFluid>>>
  getAvailableFluids() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableFluids, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.FlammableFluid>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.FlammableFluid>>(
                    this,
                    Invocation.method(#getAvailableFluids, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.FlammableFluid>>>);
}
