// Mocks generated by Mockito 5.4.6 from annotations
// in app_froid/test/features/ruler/domain/usecases/calculate_simple_ruler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_froid/core/error/failures.dart' as _i5;
import 'package:app_froid/features/ruler/domain/entities/calculation_result.dart'
    as _i6;
import 'package:app_froid/features/ruler/domain/entities/fluid.dart' as _i7;
import 'package:app_froid/features/ruler/domain/repositories/ruler_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RulerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRulerRepository extends _i1.Mock implements _i3.RulerRepository {
  MockRulerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CalculationResult>> calculateSimple({
    required _i7.Fluid? fluid,
    double? temperature,
    double? pressure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateSimple, [], {
              #fluid: fluid,
              #temperature: temperature,
              #pressure: pressure,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.CalculationResult>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.CalculationResult>(
                    this,
                    Invocation.method(#calculateSimple, [], {
                      #fluid: fluid,
                      #temperature: temperature,
                      #pressure: pressure,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CalculationResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CalculationResult>> calculateAdvanced({
    required _i7.Fluid? fluid,
    required String? car1,
    required double? val1,
    required String? car2,
    required double? val2,
    required String? carNeed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateAdvanced, [], {
              #fluid: fluid,
              #car1: car1,
              #val1: val1,
              #car2: car2,
              #val2: val2,
              #carNeed: carNeed,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.CalculationResult>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.CalculationResult>(
                    this,
                    Invocation.method(#calculateAdvanced, [], {
                      #fluid: fluid,
                      #car1: car1,
                      #val1: val1,
                      #car2: car2,
                      #val2: val2,
                      #carNeed: carNeed,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CalculationResult>>);
}
