// Mocks generated by Mockito 5.4.6 from annotations
// in app_froid/test/features/fluid_custom/data/repositories/fluid_custom_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_froid/features/fluid_custom/data/datasources/fluid_custom_local_datasource.dart'
    as _i2;
import 'package:app_froid/features/fluid_custom/data/models/fluid_custom_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FluidCustomLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFluidCustomLocalDataSource extends _i1.Mock
    implements _i2.FluidCustomLocalDataSource {
  MockFluidCustomLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FluidCustomModel>> getFluidCustoms() =>
      (super.noSuchMethod(
            Invocation.method(#getFluidCustoms, []),
            returnValue: _i3.Future<List<_i4.FluidCustomModel>>.value(
              <_i4.FluidCustomModel>[],
            ),
          )
          as _i3.Future<List<_i4.FluidCustomModel>>);

  @override
  _i3.Future<void> saveFluidCustoms(List<_i4.FluidCustomModel>? fluids) =>
      (super.noSuchMethod(
            Invocation.method(#saveFluidCustoms, [fluids]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addFluidCustom(_i4.FluidCustomModel? fluid) =>
      (super.noSuchMethod(
            Invocation.method(#addFluidCustom, [fluid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateFluidCustom(int? index, _i4.FluidCustomModel? fluid) =>
      (super.noSuchMethod(
            Invocation.method(#updateFluidCustom, [index, fluid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFluidCustom(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#removeFluidCustom, [index]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
