// Mocks generated by Mockito 5.4.6 from annotations
// in app_froid/test/features/converter/domain/usecases/convert_pressure_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:app_froid/core/error/failures.dart' as _i4;
import 'package:app_froid/features/converter/domain/entities/conversion.dart'
    as _i5;
import 'package:app_froid/features/converter/domain/repositories/converter_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConverterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConverterRepository extends _i1.Mock
    implements _i3.ConverterRepository {
  MockConverterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Either<_i4.Failure, List<_i5.Conversion>> convertPressure({
    required double? value,
    required String? fromUnit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#convertPressure, [], {
              #value: value,
              #fromUnit: fromUnit,
            }),
            returnValue: _FakeEither_0<_i4.Failure, List<_i5.Conversion>>(
              this,
              Invocation.method(#convertPressure, [], {
                #value: value,
                #fromUnit: fromUnit,
              }),
            ),
          )
          as _i2.Either<_i4.Failure, List<_i5.Conversion>>);

  @override
  _i2.Either<_i4.Failure, List<_i5.Conversion>> convertTemperature({
    required double? value,
    required String? fromUnit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#convertTemperature, [], {
              #value: value,
              #fromUnit: fromUnit,
            }),
            returnValue: _FakeEither_0<_i4.Failure, List<_i5.Conversion>>(
              this,
              Invocation.method(#convertTemperature, [], {
                #value: value,
                #fromUnit: fromUnit,
              }),
            ),
          )
          as _i2.Either<_i4.Failure, List<_i5.Conversion>>);
}
