// Mocks generated by Mockito 5.4.6 from annotations
// in app_froid/test/features/lfl_volume/data/repositories/lfl_volume_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_froid/features/lfl_volume/data/datasources/lfl_volume_local_datasource.dart'
    as _i3;
import 'package:app_froid/features/lfl_volume/data/models/flammable_fluid_model.dart'
    as _i6;
import 'package:app_froid/features/lfl_volume/data/models/lfl_result_model.dart'
    as _i2;
import 'package:app_froid/features/lfl_volume/domain/entities/lfl_parameters.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLflResultModel_0 extends _i1.SmartFake
    implements _i2.LflResultModel {
  _FakeLflResultModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LflVolumeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLflVolumeLocalDataSource extends _i1.Mock
    implements _i3.LflVolumeLocalDataSource {
  MockLflVolumeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.LflResultModel> calculateLflVolume(
    _i5.LflParameters? parameters,
    double? safetyFactor,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateLflVolume, [parameters, safetyFactor]),
            returnValue: _i4.Future<_i2.LflResultModel>.value(
              _FakeLflResultModel_0(
                this,
                Invocation.method(#calculateLflVolume, [
                  parameters,
                  safetyFactor,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.LflResultModel>);

  @override
  _i4.Future<List<_i6.FlammableFluidModel>> getAvailableFluids() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableFluids, []),
            returnValue: _i4.Future<List<_i6.FlammableFluidModel>>.value(
              <_i6.FlammableFluidModel>[],
            ),
          )
          as _i4.Future<List<_i6.FlammableFluidModel>>);
}
