// Mocks generated by Mockito 5.4.6 from annotations
// in app_froid/test/features/refrigerant_charge/presentation/bloc/refrigerant_charge_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:app_froid/core/error/failures.dart' as _i6;
import 'package:app_froid/core/usecases/usecase.dart' as _i8;
import 'package:app_froid/features/refrigerant_charge/domain/entities/charge_parameters.dart'
    as _i11;
import 'package:app_froid/features/refrigerant_charge/domain/entities/charge_result.dart'
    as _i10;
import 'package:app_froid/features/refrigerant_charge/domain/entities/fluid.dart'
    as _i7;
import 'package:app_froid/features/refrigerant_charge/domain/repositories/refrigerant_charge_repository.dart'
    as _i2;
import 'package:app_froid/features/refrigerant_charge/domain/usecases/calculate_refrigerant_charge.dart'
    as _i9;
import 'package:app_froid/features/refrigerant_charge/domain/usecases/get_available_fluids.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRefrigerantChargeRepository_0 extends _i1.SmartFake
    implements _i2.RefrigerantChargeRepository {
  _FakeRefrigerantChargeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAvailableFluids].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAvailableFluids extends _i1.Mock
    implements _i4.GetAvailableFluids {
  MockGetAvailableFluids() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RefrigerantChargeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRefrigerantChargeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RefrigerantChargeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Fluid>>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, List<_i7.Fluid>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i7.Fluid>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Fluid>>>);
}

/// A class which mocks [CalculateRefrigerantCharge].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculateRefrigerantCharge extends _i1.Mock
    implements _i9.CalculateRefrigerantCharge {
  MockCalculateRefrigerantCharge() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RefrigerantChargeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRefrigerantChargeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RefrigerantChargeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i10.ChargeResult>> call(
    _i11.ChargeParameters? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i10.ChargeResult>>.value(
                  _FakeEither_1<_i6.Failure, _i10.ChargeResult>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i10.ChargeResult>>);
}
